name: elite_counsel
description: A new Flutter application.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_html:
  firebase_auth: ^3.1.1
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  sms_autofill: ^2.1.2
  visibility_detector: ^0.2.0
  flutter_neumorphic:
    git:
      url: https://github.com/tsvillain/Flutter-Neumorphic.git
  intl_phone_field: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  dot_navigation_bar: ^1.0.1+3
  photo_view: ^0.12.0
  ionicons: ^0.1.2
  mime: ^1.0.0
  open_file: ^3.1.0
  file_picker: ^4.1.1
  linkify: ^4.0.0
  flutter_linkify: ^5.0.0
  firebase_storage: ^10.0.3
  url_launcher: ^6.0.3
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  flutter_easyloading: ^3.0.0
  date_field: ^2.0.1
  share: ^2.0.4
  in_app_review: ^2.0.2
  liquid_swipe: ^2.1.0
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.1
  flutter_feather_icons: ^2.0.0+1
  timelines: ^0.1.0
  palette_generator: ^0.3.0
  youtube_player_iframe: ^2.2.2
  youtube_player_flutter: ^8.0.0
  floating_bottom_navigation_bar: ^1.5.2
  rating_dialog: ^2.0.3
  store_redirect: ^2.0.0
  cached_network_image: ^3.2.0
  flutter_svg: ^0.23.0+1
  accordion: ^2.1.2
  salesiq_mobilisten: ^1.0.1
  zoho_chat: ^0.0.1
  ripple_navigation: ^1.0.5
  device_preview: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

#  fonts:
#    - family:  Metropolis
#      fonts:
#        - asset: assets/fonts/Metropolis/Metropolis-Black.otf
#          weight: 900
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraBold.otf
#          weight: 800
#        - asset: assets/fonts/Metropolis/Metropolis-Bold.otf
#          weight: 700
#        - asset: assets/fonts/Metropolis/Metropolis-SemiBold.otf
#          weight: 600
#        - asset: assets/fonts/Metropolis/Metropolis-Medium.otf
#          weight: 500
#        - asset: assets/fonts/Metropolis/Metropolis-Regular.otf
#          weight: 400
#        - asset: assets/fonts/Metropolis/Metropolis-Light.otf
#          weight: 300
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraLight.otf
#          weight: 200
#        - asset: assets/fonts/Metropolis/Metropolis-Thin.otf
#          weight: 200
#        - asset: assets/fonts/Metropolis/Metropolis-BlackItalic.otf
#          style: italic
#          weight: 900
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraBoldItalic.otf
#          style: italic
#          weight: 800
#        - asset: assets/fonts/Metropolis/Metropolis-BoldItalic.otf
#          style: italic
#          weight: 700
#        - asset: assets/fonts/Metropolis/Metropolis-SemiBoldItalic.otf
#          style: italic
#          weight: 600
#        - asset: assets/fonts/Metropolis/Metropolis-MediumItalic.otf
#          style: italic
#          weight: 500
##        - asset: assets/fonts/Metropolis/Metropolis-Italic.otf
##          style: italic
##          weight: 400
#        - asset: assets/fonts/Metropolis/Metropolis-LightItalic.otf
#          style: italic
#          weight: 300
#        - asset: assets/fonts/Metropolis/Metropolis-ExtraLightItalic.otf
#          style: italic
#          weight: 200
#        - asset: assets/fonts/Metropolis/Metropolis-ThinItalic.otf
#          style: italic
#          weight: 200