# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.14.0'
  pod "Firebase/Analytics"
  pod "Firebase/Crashlytics"
  pod "Firebase/Firestore"

  # Pods for Runner

end